version: '2'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: DevBlog
    ports:
      - 5432:5432


  app:
    image: 'dev-blog-app:latest'
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/DevBlog