version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 221103
      POSTGRES_DB: DevBlog


  app:
    image: 'dev-blog-app:latest'
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: app
    ports:
      - 8000:8080
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/DevBlog