spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/DevBlog
    username: postgres
    password: 221103

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate